### PR TITLE
Intermediate Ruby: OOP

### PR DESCRIPTION
**Pull request by ebeagusamuel**
# Milestone2: User interface
- Displayed prompt for users.
- Displayed game board.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @ebeagusamuel and @krys2fa 
### You have done a good job so far :clap: However, you need to add more in the game in this milestone. The functionalities that are required here:
- [ ] game asks players for their names
- [ ] game tells which player turn it is
- [ ] game asks the player to select from available moves
- [ ] game informs player if the selected move is invalid
- [ ] game displays board after the player move
- [ ] game informs player if the selected move is a winning move
- [ ] game informs player if the selected move is a draw move
- [ ] game repeats all actions for the next player's move

### and you need this inside a loop to repeatedly do the tasks 
### Make all these changes and submit for another code review. Good luck.

- Happy coding!

By Raymond
slack @iamraymond

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work team! @ebeagusamuel and @krys2fa :rocket:
You have done a great job thus far, please consider my comments below, make the appropriate changes, and request another review!

#### Draws
Your logic doesn't currently handle the edge case of when there's a draw. It should announce the draw and stop the game/ask for a restart. Right now it throws an exception which isn't great behavior.

#### Wins
Please consider announcing the winner of the concluded game. Currently, the game just stops.

#### Stickler errors
You have done very nicely by including stickler in your project as requested! However, you need to ensure that all errors it throws are appropriately addressed before you request a PR review. Please look into this, address appropriately and request another review. 


##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by stratospherique — APPROVED** [review]
### Great work implementing the suggested changes :clap: Congrats, the project is approved :heavy_check_mark: You may merge :+1: :+1: 

Keep up the good work :muscle: 
**_Ahmed Mahfoudh_**

**Comment by krys2fa** [comment]
Thanks @stratospherique

**Pull request merged**
